### ISSUE TITLE
./gradlew build returns BUILD FAILED

### ISSUE THREAD

**Issue by OrdonTeam** [Wojtek1234/GithubApiRequester#1]
FAILURE: Build failed with an exception.
- Where:
  Build file '/home/karol/Workspaces/GithubApiRequester/app/build.gradle' line: 20
- What went wrong:
  A problem occurred evaluating project ':app'.
  
  > Neither path nor baseDir may be null or empty string. path='null' basedir='/home/karol/Workspaces/GithubApiRequester/app'
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.097 secs

**Comment by Wojtek1234** [comment]
my bad, it should not be there
