### ISSUE TITLE
After removing signing from build gradle, build still fails

### ISSUE THREAD

**Issue by OrdonTeam** [Wojtek1234/GithubApiRequester#2]
./gradlew build
:app:processDebugResources
/home/karol/Workspaces/GithubApiRequester/app/src/main/res/layout/activity_user_detail.xml:52:22-43: AAPT: No resource found that matches the given name (at 'src' with value '@drawable/follow_icon').

:app:processDebugResources FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:processDebugResources'.
  
  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/karol/Android/Sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.646 secs

**Comment by Wojtek1234** [comment]
icon added to project
