### ISSUE TITLE
After resolving problem with resouces, build still fails

### ISSUE THREAD

**Issue by OrdonTeam** [Wojtek1234/GithubApiRequester#3]
./gradlew build
/home/karol/Workspaces/GithubApiRequester/app/src/main/java/com/wojciechmaciejewski/githubapirequester/App.kt: (25, 32): Unresolved reference: DaggerRuntimeApplicationComponent
:app:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:compileDebugKotlin'.
  
  > Compilation error. See log for more details
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.352 secs

**Comment by Wojtek1234** [comment]
To jest jakiś dziwny problem z Dagger2 i Kotlin i generowaniem klas przez Daggera.

Myślałem że to może na moim kompie tak dziwnie działa ale widzę że wszędzie tak się dzieje.

Żeby zbudować kod pierwszy raz zakomentuj proszę metodę initializeInjection() z App.kt w sensie jej ciało. Po tym ruszy build i później już cały projekt

nie mam pojęcia dlaczego tak się dzieje. spróbuję znaleźć odpowiedź

**Comment by Wojtek1234** [comment]
Ok , i moved creation of application component to Java class, now it should build without any changes

**Comment by OrdonTeam** [comment]
It works now
